version: '3.5'
services:

  pycsw:
    build:
      context: ./pycsw/
      dockerfile: Dockerfile
    container_name: senda-csw
    image: metno/senda-csw
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      INDEXDB: "true"
      METADATA: "/mmd/nbs"
      OUTPUT_ISO: "/home/pycsw/iso_xml/nbs"
    volumes:
      - ./Volumes/pycsw/conf/pycsw.cfg:/etc/pycsw/pycsw.cfg
      - ./Volumes/pycsw/commands/pycsw_setup.sh:/usr/local/bin/pycsw_setup.sh
      - ./Volumes/pycsw/commands/mmd2isofix.py:/usr/local/bin/mmd2isofix.py
      - ./Volumes/pycsw/commands/mmd-to-iso.xsl:/usr/local/share/mmd-to-iso.xsl
      - ./Volumes/mmd:/mmd:ro

    entrypoint:
      - /bin/sh
      - /usr/local/bin/pycsw_setup.sh

  dynamic-geoassets-api:
    build:
      context: ./dynamic-geoassets-api/
      dockerfile: Dockerfile
    container_name: senda-dynamic-geoassets-api
    image: metno/senda-dynamic-geoassets-api
    ports:
      - "8080:8080"
    restart: unless-stopped

  data-dashboard:
    build:
      context: ./data-dashboard/
      dockerfile: Dockerfile
    container_name: senda-data-dashboard
    image: metno/senda-data-dashboard
    ports:
      - "8081:80"
    restart: unless-stopped