version: '3.5'
services:

  pycsw:
    build:
      context: ./CSW/
      dockerfile: Dockerfile
    container_name: senda-csw
    image: metno/senda-csw
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      INDEXDB: "true"
      METADATA: "/data/mmd_xml/nbs"
      OUTPUT_ISO: "/data/iso_xml/nbs"
    volumes:
      - ./Volumes/CSW/conf/pycsw.cfg:/etc/pycsw/pycsw.cfg
      - ./Volumes/CSW/commands/pycsw_setup.sh:/usr/local/bin/pycsw_setup.sh
      - ./Volumes/CSW/commands/mmd2isofix.py:/usr/local/bin/mmd2isofix.py
      - ./Volumes/CSW/commands/mmd-to-iso.xsl:/usr/local/share/mmd-to-iso.xsl
      - ./Volumes/data:/data
    # command: /bin/sh /usr/local/bin/pycsw_setup.sh
    entrypoint:
      - /bin/sh
      - /usr/local/bin/pycsw_setup.sh

  dynamic-geoassets-api:
    build:
      context: ./dynamic-geoassets-api/
      dockerfile: Dockerfile
    container_name: senda-dynamic-geoassets-api
    image: metno/senda-dynamic-geoassets-api
    ports:
      - "8080:8080"
    restart: unless-stopped
