---
version: '3.4'

x-restart:
  &default-restart-policy
  unless-stopped

x-logging:
  &default-logging-policy
    driver: journald

networks:
  event-engine:
  internal:

services:
  postgis:
    image: postgis/postgis:13-master
    networks:
      internal:
        aliases:
          - postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgis}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgis}
      POSTGRES_DB: csw_db
    volumes:
      - /srv/postgis:/var/lib/postgresql/data

  #
  # catalog-service-api (pycsw)
  #

  catalog-service-api:
    image: docker.io/metno/senda-csw-catalog-service:${VERSION:-dev}
    ports:
      - "80:8000"
    networks:
      internal:
    environment:
      INDEXDB: "true"
      ISO_STORE: "/isostore"
      PYCSW_DATABASE: "postgresql://${POSTGRES_USER:-postgis}:${POSTGRES_PASSWORD:-postgis}@postgis:5432/csw_db"
    volumes:
      - ./isostore:/isostore:ro
    depends_on:
      - postgis
    logging: *default-logging-policy
    restart: *default-restart-policy

  #
  # dynamic-geoasset-api
  #

  dynamic-geoassets-api:
    image: docker.io/metno/senda-prototype:${VERSION:-dev}-dynamic-geoasset-api
    ports:
      - "8080:8080"
    logging: *default-logging-policy
    restart: *default-restart-policy

  #
  # data-dashboard
  #

  data-dashboard:
    image: docker.io/metno/senda-prototype:${VERSION:-dev}-dash-board
    ports:
      - "8081:80"
    logging: *default-logging-policy
    restart: *default-restart-policy

  #
  # event-engine components
  #

  nats:
    image: nats:2.1
    networks:
      event-engine:
        aliases:
          - nats-main
    logging: *default-logging-policy
    restart: *default-restart-policy

  event-engine-sender:
    image: docker.io/metno/senda-prototype:${VERSION:-dev}-event-engine-sender
    depends_on:
      - nats
    environment:
      NATS_SERVER: "http://nats-main:4222"
      SUBJECT: "senda"
    networks:
      - event-engine
    logging: *default-logging-policy
    restart: *default-restart-policy


  # FIXME: Find out if we're going to expose this port to the world

  event-engine-websocket-bridge:
    image: docker.io/metno/senda-prototype:${VERSION:-dev}-event-engine-websocket-bridge
    depends_on:
      - nats
    environment:
      NATS_SERVER: "http://nats-main:4222"
      SUBJECT: "senda"
    ports:
      - "8084:8084"
    networks:
      - event-engine
    logging: *default-logging-policy
    restart: *default-restart-policy

  #
  # iso-converter
  #

  iso-converter:
    image: docker.io/metno/senda-iso-converter:${VERSION:-dev}

  #
  # watchtower, let watchtower update containers automatically
  #

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging: *default-logging-policy
    restart: *default-restart-policy
