# Build
FROM golang:1.14-alpine AS build-app
WORKDIR /build/app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .
#RUN go test .
RUN go build -o sender ./cmd/sender/sender.go

# Runtime
FROM alpine

COPY --from=build-app /build/app/sender /app/

WORKDIR /app
USER nobody:nogroup

ENTRYPOINT ["/app/sender"]
