# Build
FROM golang:1.14-alpine AS build-app
WORKDIR /build/app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .
#RUN go test .
RUN go build -o websocket-bridge ./cmd/websocket-bridge/websocket-bridge.go

# Runtime
FROM alpine

COPY --from=build-app /build/app/websocket-bridge /app/

WORKDIR /app
USER nobody:nogroup

EXPOSE 8084

ENTRYPOINT ["/app/websocket-bridge"]